name: "Code Lint Check"
on: [push, pull_request]

jobs:
  quality:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Biome
        uses: biomejs/setup-biome@v1
        with:
          version: latest
      - name: Run Biome
        run: pnpm run ui:check:ci
